[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test_foundry'
cache_path  = 'cache_forge'

## 0.8.21 breaks
solc_version = '0.8.18'


## See hardhat.export.ts for runs
optimizer = true
optimizer_runs = 100

## Undo steps to avoid compatibility with via_ir
optimizer_steps = ''

## Enable_ir because of stack too depp
via_ir = true
